import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Breadcrumbs from "@/components/Breadcrumbs";
import { Toaster } from "@/components/ui/sonner";
import StoreProvider from "@/providers/StoreProvider";
import { poppins } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <Navbar />
        <div className="container grid grid-cols-12 my-16">
          <div className="col-span-12 lg:col-span-8 lg:col-start-3">
            <StoreProvider>
              <Breadcrumbs />
            </StoreProvider>
            {children}
          </div>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
